数値計算のサンプルを追加
dlang-jp/Cookbook pull request #102
Opened 2021-03-13 09:12 UTC by lempiji

まだ内容少ないですが、数値計算系で必要となる記述をまとめるモジュール追加しました。

`approxEqual` は 2.096.0 で非推奨になってしまったので `isClose` のみです。

`unittest` のモジュールにまだ `approxEqual` が残っているので `isClose` に書き換える必要がありそうですが、これは別件として対応したいと思います。

2021-03-13 09:27 UTC, outlandkarasu commented
LGTM

2021-03-13 09:45 UTC, shoo requested changes
unittests_exampleに浮動小数点数をテストする方法が既に存在しています。(こいつがおもいっきりdeprecatedを連呼する)
内容的に、どちらかというと今回追加するこちらに(内容をメンテナンスして)移動するべきだと思います。

2021-04-17 05:26 UTC, lempiji commented
検索性が低い状態なので、両方に書いてあるほうが親切かと思い、両方残してisCloseで内容統一しました

2021-04-17 06:09 UTC, shoo approved these changes
LGTM

2021-04-17 06:09 UTC, merged