RefCountedの例を追加する
dlang-jp/Cookbook pull request #121
Opened 2021-06-05 05:18 UTC by outlandkarasu

ライブラリなどで良くみられる、structで内部的にPayloadを定義して、そちらをRefCountedで管理する例にしてみました。
もう少し良い例があればコメントください。

2021-06-05 05:27 UTC, kubo39 commented
例示だと実際に参照カウントが上がったり下がったりするのを確認する方法が紹介されている気がします。
(`refCount` というのがそれにあたりますが、わりと `_refCounted._store._count` で生アクセスしてるケースがよくあるのでこのへん地味に違ってたりするのかも？)

2021-06-05 05:51 UTC, shoo commented on source/typecons_example.d
> +            int value;
```suggestion
            // Payload解放処理
            // Container初期化直後などでPayload.initに対しても呼び出される点に注意が必要です。
            // 空のポインタやリソースハンドル等の破棄が安全に行われるようにする必要があります。
            // このため、初期値だったら解放しない、というロジックが必要です。
            ~this() @nogc nothrow @safe scope
            {
                if (value != int.max)
                {
                    // ここでは解放時点の情報を記録します。
                    lastDestructed = value;
                    ++destructedCount;
                }
                ++destructorCallCount;
            }

            int value = int.max;
```

destructorCallCountは新たに追加して、デストラクタが呼ばれた回数と、実際に破棄のロジックが走った回数を分けてやったら少しイメージわきやすいかもしれません

2021-06-05 08:39 UTC, lempiji requested changes
```
コピー不能であったり、デストラクタを持っていたりする構造体を複数の変数で共有、参照する例です。

ポインタでも参照させることは可能ですが、デストラクタの呼び出しを自動で安全に行うために `RefCounted` を使う方法があります。
内部的には参照カウンタで管理されます。
```
といった感じの説明でいかがでしょう
（単に機能の使い方というよりは用途や目的を示す感じで）

2021-06-19 15:10 UTC, outlandkarasu commented
以下の通り修正してみました。

* `RefCounted!Payload`を直接扱う形の例にした。
* `pureMalloc`・`pureFree`で実際にリソース確保・解放を行うコードにした。
* `refCountedStore.refCount`による参照カウントの確認を追加した。
* 初期化時のデストラクタ呼び出しについてはコメントの説明のみに留め、呼び出し回数等のチェックは消した。

2021-06-21 13:44 UTC, shoo requested changes

2021-06-21 13:44 UTC, shoo commented on source/typecons_example.d
> +    auto resource1 = cast(int*) pureMalloc(int.sizeof);
pureMalloc/pureFreeの対称性のため、コンストラクタでpureMallocした方が良いと思います。

2021-06-23 13:35 UTC, shoo approved these changes

2021-07-24 05:34 UTC, lempiji approved these changes

2021-07-24 05:34 UTC, merged