拡張子操作、ファイル移動、globによるファイル列挙の例を追加
dlang-jp/Cookbook pull request #124
Opened 2021-06-19 07:01 UTC by lempiji

2021-06-19 07:33 UTC, shoo requested changes

2021-06-19 07:33 UTC, shoo commented on source/file_example.d
> +    assert(testFiles == [
列挙順はプラットフォーム依存なので、事前にソートした方が良いと思います。

2021-06-19 07:33 UTC, shoo commented on source/file_example.d
> +    scope (exit) rmdirRecurse("temp1");
マルチスレッドでテストすると不都合出るかもしれないです。UUIDとかでユニークな名前の一時ディレクトリ作った方がいいかも？
ここ以外にも言えることですが。

2021-06-19 07:33 UTC, shoo commented on source/file_example.d
> +    assert(extension("/test/hoge/fuga") == "");
コーナーケース的には、".txt.old"みたいな拡張子があった場合どうなるか示した方がいいかもです。これで一回しくじりしたことがあるので…。

2021-07-24 08:11 UTC, shoo commented on source/file_example.d
> +    scope (exit) rmdirRecurse("temp1");
これはやるとしても別の案件として分けた方が良いですね。

2021-07-24 08:12 UTC, lempiji commented on source/file_example.d
> +    assert(extension("/test/hoge/fuga") == "");
パターン追加してみました。ロジック解説みたいな感じですが、これはこれで一貫性が見れて良さそうですね

2021-07-24 08:12 UTC, lempiji commented on source/file_example.d
> +    scope (exit) rmdirRecurse("temp1");
テスト時間考えるとsillyあたり追加したい気もするので、やるなら一気にということでIssue追加しておきます

2021-07-24 08:12 UTC, lempiji commented on source/file_example.d
> +    assert(testFiles == [
ソート追加しました

2021-07-24 08:13 UTC, shoo approved these changes

2021-07-24 08:13 UTC, merged