vibe.dを使った認証の追加
dlang-jp/Cookbook pull request #137
Opened 2021-08-27 14:03 UTC by shoo

認証とか権限とかセッションについて説明するページが必要かなと思って作りました。

2021-08-28 08:27 UTC, lempiji requested changes

2021-08-28 08:27 UTC, lempiji commented on thirdparty/vibe-d/source/vibed_usage/auth.d
> +            // セッション情報を保存します
認証APIに見えて素通りなので、コメントで補足しておくと良い気がしました

```suggestion
            // セッション情報を保存します
            // 認証API風ですが、パスワード等のセキュリティは考慮していません
```

2021-08-28 08:27 UTC, lempiji commented on thirdparty/vibe-d/source/vibed_usage/auth.d
> +セッション
将来的にRedisを使った分散ストアなどについて書くことを考えると、認証とは分けておきたいです。
説明用として前段に欲しい気はするので、TODOとして移設のメモ残せないでしょうか

2021-08-28 08:27 UTC, lempiji commented on thirdparty/vibe-d/source/vibed_usage/auth.d
> +
// 認証なしで認証が必要なところを閲覧
のパターンがほしいです。確認としては401が得られる、ということだけ分かれば良いかと（話が進むとエラーページを変えたいとか色々出てきてしまいますが）

2021-09-18 10:01 UTC, shoo commented on thirdparty/vibe-d/source/vibed_usage/auth.d
> +セッション
精製されたドキュメントに載らないように、ソースコード上のコメントとして残しました。

2021-09-18 10:03 UTC, shoo commented on thirdparty/vibe-d/source/vibed_usage/auth.d
> +
https://github.com/dlang-jp/Cookbook/pull/137/files#diff-fffb484592b3c8832538b661aed340b8c52612808af7786d6f9d5643e956e127R457
追加しました

2022-01-28 12:19 UTC, kubo39 commented on thirdparty/vibe-d/source/vibed_usage/auth.d
> +- https://github.com/vibe-d/vibe.d/issues/2597
ここはoudatedな情報なので修正してもらえると :pray:

2022-02-19 09:55 UTC, shoo commented
まれに以下の問題が生じてCIがエラーになります。

```
auth.d(517): object.Exception@vibe-core-1.22.0\vibe-core\source\vibe\core\net.d(811): Connection closed while writing data.
vibed_usage.auth.__unittest_L322_C1.__lambda11.__lambda6 at \Cookbook\thirdparty\vibe-d\source\vibed_usage\auth.d(461)
```

https://github.com/dlang-jp/Cookbook/runs/5257809010?check_suite_focus=true

ローカルでは再現せず、そもそもCIでも出るときと出ないときがあります。
力不足により私には原因わからず…。原因わかる方いたらご協力お願いいたします。
2022/3/31まで待って原因不明だったら、権限設定の部分は除外しようと思います。

2022-07-23 05:22 UTC, lempiji approved these changes

2022-07-23 05:37 UTC, merged