配列をRangeとして扱う例追加
dlang-jp/Cookbook pull request #150
Opened 2022-02-19 05:11 UTC by outlandkarasu

2022-02-19 05:49 UTC, lempiji requested changes

2022-02-19 05:49 UTC, lempiji commented on source/range_example.d
> +    // 動的配列とRangeのどちらにも使用できる関数が定義できます。
ここが主題かなと思われ、「動的配列とRangeのどちらにも対応した関数を書く方法」というタイトルが良いかなと思いましたがいかがでしょう。

2022-02-19 08:34 UTC, shoo requested changes

2022-02-19 08:34 UTC, shoo commented on source/range_example.d
> +    values = [1, 2, 3];
順番を入れ替えた際にここでエラーが発生するようになりました。事前に`int[] values;`って感じに定義しておく必要があります。

2022-02-21 13:48 UTC, outlandkarasu commented on source/range_example.d
> +    values = [1, 2, 3];
凡ミスですみません、修正しました……。

2022-05-21 05:16 UTC, shoo approved these changes

2022-05-21 05:22 UTC, lempiji approved these changes

2022-05-21 05:22 UTC, merged