浮動小数点型の扱いを追加
dlang-jp/Cookbook pull request #152
Opened 2022-02-19 07:27 UTC by lempiji

floatingプロパティの例を追加しました。

2022-02-19 08:17 UTC, shoo requested changes

2022-02-19 08:17 UTC, shoo commented on source/data/json_example.d
> +    assert(jvz.floating == 1.25);
浮動小数点数を == で比較するのはあまりよくないので、isCloseを使ったほうが良さそうです。

2022-07-23 05:47 UTC, lempiji commented on source/data/json_example.d
> +    assert(jvz.floating == 1.25);
修正しました！

2022-07-23 06:38 UTC, shoo approved these changes

2022-07-23 06:42 UTC, merged