CI関連の更新
dlang-jp/Cookbook pull request #193
Opened 2023-04-22 08:15 UTC by shoo

以下に対応しました。

- 一時的にdmd-beta版を使っていたのを、dmd-masterへ戻す
- fork先のGitHubリポジトリでtestブランチでもCIが実行されるようにする
- CI関連の依存モジュールのバージョンアップ
- asdfのテストが入っていなかったのを修正
- ut.dファイルを削除し、代わりに--DRT-covopt引数を使用するようにした

2023-04-22 09:18 UTC, lempiji requested changes

2023-04-22 09:18 UTC, lempiji commented on thirdparty/vibe-d/source/vibed_usage/rest.d
> +    auto exitCode = runEventLoop();
CI通ってるようですが、関係ない変更が混ざっていそうなのでここだけ戻してはどうでしょうか

```suggestion
    auto exitCode = runApplication();
```

2023-04-22 13:16 UTC, shoo commented on thirdparty/vibe-d/source/vibed_usage/rest.d
> +    auto exitCode = runEventLoop();
この変更は、--DRT-covoptを指定する際にvibe.dのrunApplicationの中にあるコンパイルスイッチを判定する部分に引っかかって強制終了してしまうのを防ぐための変更です。
https://github.com/vibe-d/vibe-core/blob/df666958072bffa678a16fa67b66ed644fb1b21a/source/vibe/core/core.d#L92

2023-09-23 06:30 UTC, lempiji approved these changes

2023-09-23 06:30 UTC, merged