Fix CI broken
dlang-jp/Cookbook pull request #210
Opened 2024-11-12 13:51 UTC by lempiji

#209 ＋パス修正版です

2024-11-12 14:01 UTC, shoo commented
`actions/upload-artifact@v4` これになって隠しファイルを無視するようになったため、 `.cov` がアップロードされないんだと思います。
`include-hidden-files: true` が必要っぽいです。
https://github.com/shoo/bsky/blob/d1e49d15e250b45d9a98d9246489abbba306296b/.github/workflows/main.yml#L132-L137

ちなみにこれに対応した `actions/download-artifact@v4` が以下。
https://github.com/shoo/bsky/blob/d1e49d15e250b45d9a98d9246489abbba306296b/.github/workflows/main.yml#L353-L356

2024-11-12 14:51 UTC, lempiji commented
unittestでカバレッジが出力されないですね…
https://github.com/dlang-jp/Cookbook/actions/runs/11799626616/job/32868613595#step:6:12
`Warning: No files were found with the provided path: .cov. No artifacts will be uploaded.`

Windowsに限らず他も同じっぽいです。もしやCIだから何か止められている…？

2024-11-12 14:52 UTC, shoo requested changes

2024-11-12 14:52 UTC, shoo commented on source/process_example.d
改行コードがCRLFになってます

2024-11-12 14:52 UTC, shoo commented on .github/workflows/pr.yml
> +
include-hidden-files: true

2024-11-12 14:52 UTC, shoo commented on .github/workflows/pr.yml
>            path: .cov
include-hidden-files: true

2024-11-12 14:52 UTC, shoo commented on .github/workflows/pr.yml
>            path: .cov
include-hidden-files: true

2024-11-12 20:55 UTC, kubo39 commented on source/process_example.d
ついでなのでeditorconfig足しちゃいましょう。

2024-12-29 11:22 UTC, lempiji reviewed
CI通すために諸々修正しました。

2024-12-29 11:22 UTC, lempiji commented on source/process_example.d
.dと.ymlを追加しました

2024-12-29 11:22 UTC, lempiji commented on .github/workflows/pr.yml
> +
追加

2024-12-29 11:22 UTC, lempiji commented on .github/workflows/pr.yml
>            path: .cov
追加

2024-12-29 11:22 UTC, lempiji commented on .github/workflows/pr.yml
>            path: .cov
追加

2024-12-29 11:22 UTC, lempiji commented on .github/workflows/master.yml
追加

2025-01-30 11:31 UTC, shoo approved these changes

2025-01-30 11:31 UTC, merged