プログラムの整形文字列表現の例を追加
dlang-jp/Cookbook pull request #90
Opened 2020-02-19 14:19 UTC by shoo

2020-10-03 03:32 UTC, lempiji requested changes
二重かっこ削ればあとは良いと思います。

2020-10-03 03:32 UTC, lempiji commented on source/string_example.d
> +{{
二重なのは削って良さそうなのでsuggestionしてみます。

```suggestion
{
```

2020-10-03 03:32 UTC, lempiji commented on source/string_example.d
> +}}
こちらも削って良さそうです

```suggestion
}
```

2020-10-05 11:05 UTC, shoo reviewed
Fix typo

2021-03-13 07:08 UTC, merged